name: Golang-CI
on: [push]

jobs:

  lint:
    name: Run Golang-CI Linter
    runs-on: ubuntu-latest

    steps:
      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Vendor dependencies
        run: go mod vendor

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33.0