name: Tests
on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          go install github.com/mfridman/tparse/...@latest
          go test -race ./... -v -short -json -timeout=120s --failfast -p=1 -coverprofile=coverage.txt | tparse -all -notests -follow

      - name: Build
        run: go build -o githunt
