name: testing
on: [ push ]

jobs:

  test:
    name: testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: 386
          - os: linux
            arch: amd64
          - os: darwin
            arch: 386
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
      - name: do stuff
        run: echo ${{ matrix.os }} ${{ matrix.arch }}