name: Tests
on: [ push ]

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"

    steps:
      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          GO111MODULE=off go get -v github.com/mfridman/tparse/...
          go test ./... -short -v -race --failfast -coverprofile=coverage.txt -covermode=atomic -json | tparse -all -notests -dump

      - name: Build
        run: go build -o githunt